### ISSUE TITLE
Turbo also a networking suite.

### ISSUE THREAD

**Issue by kernelsauce** [LewisJEllis/awesome-lua#13]
Seems like it is listed as a web framework, which really isnt true. While it does have a HTTP module it is also very helpfull for high performance TCP/UDP networking applications.

**Comment by LewisJEllis** [comment]
Hi John - thanks for the note, and for Turbo!

The "web platforms" section is meant for this sort of thing, but it seems in hindsight that "web" is too specific there. I think it would be appropriate to change the section to "Networking Platforms" or "Web/Networking Platforms".

How does "turbo - Event-driven, non-blocking, LuaJIT-based networking suite and framework inspired by Tornado" sound for Turbo's description?

**Comment by kernelsauce** [comment]
Web/Networking Platforms might be the best of the two as it clearly states that there are two categories... Its not all web platforms that works with other than HTTP networking and also many networking platforms does not include any HTTP specifics. As for the description, I think your suggestion sound good.
