### ISSUE TITLE
Add lua-enet

### ISSUE THREAD

**Issue by rokf** [LewisJEllis/awesome-lua#19]
http://leafo.net/lua-enet/ to networking

**Comment by ghost** [comment]
done here: https://github.com/AKDev21/awesome-lua

**Comment by ghost** [comment]
Update: i removed it from https://github.com/AKDev21/awesome-lua because it's outdated

**Comment by rokf** [comment]
I'm closing this issue because either project doesn't seem to be actively worked on anymore. Thanks for the ping @AKDev21 😉
